<a href="https://colab.research.google.com/github/yestrella14/DS-Unit-1-Sprint-2-Statistics/blob/master/LS_DS_122_Chi2_Tests_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment - Practice Chi^2 Tests

Use the following dataset relating to math scores of students in two different Portugese schools:

<https://archive.ics.uci.edu/ml/datasets/Student+Performance>

### 1) Load the dataset specifically relating to math scores as a new dataframe.

There are two datasets in the `student.zip` file, make sure you use `student-mat.csv`.


In [5]:
# YOUR WORK HERE
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip

--2020-07-29 01:49:08--  https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20478 (20K) [application/x-httpd-php]
Saving to: ‘student.zip.4’

student.zip.4       100%[===================>]  20.00K  --.-KB/s    in 0.03s   

2020-07-29 01:49:08 (682 KB/s) - ‘student.zip.4’ saved [20478/20478]



In [6]:
!unzip student.zip

Archive:  student.zip
replace student-mat.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: no
replace student-por.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: N


In [8]:
#Import the libraries
import numpy as np
import pandas as pd
from scipy.stats import chisquare #one way chi squared test


In [9]:
#Read the dataset

students1 = pd.read_csv('student-mat.csv', sep=';')
print(students1.shape)
students1.head(3)

(395, 33)


school sex  age address famsize Pstatus  ...  Walc  health absences G1 G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        6  5  6   6
1     GP   F   17       U     GT3       T  ...     1       3        4  5  5   6
2     GP   F   15       U     LE3       T  ...     3       3       10  7  8  10

[3 rows x 33 columns]

In [ ]:
#students2 = pd.read_csv('student-por.csv', sep=';')
#print(students2.shape)
#students2.head(3)

In [ ]:
#append the dfs
#student_mat_por = [students1, students2]
#students = students1.append(students2)

In [10]:
students1.sample(5)

school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
117     GP   M   16       U     GT3       T  ...     1       5        0  13  14  13
115     GP   M   16       U     GT3       T  ...     2       5        2  15  15  16
353     MS   M   19       R     GT3       T  ...     3       5        4   8   8   8
48      GP   M   15       U     GT3       T  ...     2       5        2  15  15  14
84      GP   F   15       U     GT3       T  ...     3       4        2   9  10  10

[5 rows x 33 columns]

In [11]:
students1['age'].value_counts()

16    104
17     98
18     82
15     82
19     24
20      3
22      1
21      1
Name: age, dtype: int64

In [12]:
print(students1.columns.value_counts())

G3            1
higher        1
failures      1
paid          1
G2            1
Dalc          1
schoolsup     1
nursery       1
absences      1
health        1
famrel        1
famsize       1
G1            1
Pstatus       1
sex           1
romantic      1
reason        1
freetime      1
goout         1
traveltime    1
activities    1
Fedu          1
famsup        1
Walc          1
Medu          1
guardian      1
studytime     1
school        1
internet      1
Mjob          1
address       1
Fjob          1
age           1
dtype: int64


In [13]:
students1.describe(exclude='number')

school  sex address famsize  ... nursery higher internet romantic
count     395  395     395     395  ...     395    395      395      395
unique      2    2       2       2  ...       2      2        2        2
top        GP    F       U     GT3  ...     yes    yes      yes       no
freq      349  208     307     281  ...     314    375      329      263

[4 rows x 17 columns]

### 2) Use Chi^2 tests and `stats.chi2_contingency()` to identify:
 - Two pairs of variables that are dependent (are associated with one another).
 - Two pairs of variables that are independent (have no significant relationship).

Does it make intuitive sense why the variables in these pairs might or might not show a relationship to one another? 


In [ ]:
# YOUR WORK HERE
import stat


Two pairs of variables that are dependent (are associated with one another)

In [25]:
#lets take a look at absence and health. Asumming that there is a relationship between number of absence and poor health

In [39]:
#home to school travel time (numeric: 1 - <15 min., 2 - 15 to 30 min., 3 - 30 min. to 1 hour, or 4 - >1 hour)
students1['traveltime'].value_counts()

1    257
2    107
3     23
4      8
Name: traveltime, dtype: int64

In [42]:
students1['absences'].value_counts()

0     115
2      65
4      53
6      31
8      22
10     17
14     12
12     12
3       8
7       7
16      7
18      5
5       5
20      4
22      3
13      3
1       3
9       3
11      3
15      3
23      1
24      1
21      1
25      1
56      1
26      1
28      1
30      1
17      1
38      1
40      1
54      1
19      1
75      1
Name: absences, dtype: int64

In [43]:
absences_labels= ['0-9', '10-19', '20-29', '30-39', '40-49', '50-59', '60-69', '70-79']
absences_cutpoints = [0, 9, 19, 29, 39, 49, 59, 69, 100]

students1['absences_categories'] = pd.cut(students1['absences'], absences_cutpoints, labels=absences_labels)
students1['absences_categories'].value_counts()

0-9      197
10-19     64
20-29     13
50-59      2
30-39      2
70-79      1
40-49      1
60-69      0
Name: absences_categories, dtype: int64

In [44]:
contingency_table = pd.crosstab(students1['traveltime'], students1['absences_categories'], margins=True)

contingency_table

absences_categories  0-9  10-19  20-29  30-39  40-49  50-59  70-79  All
traveltime                                                             
1                    125     49      6      0      1      2      0  183
2                     54     13      5      2      0      0      1   75
3                     14      1      2      0      0      0      0   17
4                      4      1      0      0      0      0      0    5
All                  197     64     13      2      1      2      1  280

In [46]:
row_sums = contingency_table.iloc[0:4, 7].values
col_sums = contingency_table.iloc[4, 0:7].values

print(row_sums)
print(col_sums)

[183  75  17   5]
[197  64  13   2   1   2   1]


In [47]:
total = contingency_table.loc['All','All']
total

280

In [48]:
expected = []
for i in range(len(row_sums)):
    expected_row = []
    for column in col_sums:
        expected_val = column*row_sums[i]/total
        expected_row.append(expected_val)
    expected.append(expected_row)
    
expected = np.array(expected)
print(expected.shape)  
print(expected)

(4, 7)
[[1.28753571e+02 4.18285714e+01 8.49642857e+00 1.30714286e+00
  6.53571429e-01 1.30714286e+00 6.53571429e-01]
 [5.27678571e+01 1.71428571e+01 3.48214286e+00 5.35714286e-01
  2.67857143e-01 5.35714286e-01 2.67857143e-01]
 [1.19607143e+01 3.88571429e+00 7.89285714e-01 1.21428571e-01
  6.07142857e-02 1.21428571e-01 6.07142857e-02]
 [3.51785714e+00 1.14285714e+00 2.32142857e-01 3.57142857e-02
  1.78571429e-02 3.57142857e-02 1.78571429e-02]]


In [50]:
observed = pd.crosstab(students1['traveltime'], students1['absences_categories']).values
print(observed.shape)
observed

(4, 7)


array([[125,  49,   6,   0,   1,   2,   0],
       [ 54,  13,   5,   2,   0,   0,   1],
       [ 14,   1,   2,   0,   0,   0,   0],
       [  4,   1,   0,   0,   0,   0,   0]])

In [52]:
chi_squared, p_value, dof, expected = stats.chi2_contingency(observed)

print(f"Chi-Squared: {chi_squared}")
print(f"P-value: {p_value}")
print(f"Degrees of Freedom: {dof}") 
print("Expected: \n", np.array(expected))

NameError: ignored

In [51]:
chi_squared = ((observed - expected)**2/(expected)).sum() 
print(f"Chi-Squared: {chi_squared}")

Chi-Squared: 18.218216601393372


Two pairs of variables that are independent (have no significant relationship)


### 3) Use NumPy to perform your own chi^2 test "from scratch" 

Pick any of the chi^2 tests that you ran in part 2 and try them on your own. You should get the same results that Scipy got for all four values returned from `chi2_contingency()`

In [ ]:
# YOUR WORK HERE

## Stretch goals:

### 1. Refactor your code so it is elegant, readable, and holds reusable code in functions.

In [ ]:
# YOUR WORK HERE



### 2. Check For Understanding - Study and write your own explanations/definitions for these topics:

- What is a sample "estimate" in statistics?

- What are hypothesis test? How are they useful?

- What is a "null hypothesis?"

- What is a p-value and what does it represent?

- What does it mean for something to be "statistically significant?"

- What is a test statistic and how does it relate to a p-value?

- What are "degrees of freedom" and how are they calculated in a 1-sample, 2-sample, and chi^2 test for independence?

## Resources

- [Interactive visualize the Chi-Squared test](https://homepage.divms.uiowa.edu/~mbognar/applets/chisq.html)
- [Calculation of Chi-Squared test statistic](https://en.wikipedia.org/wiki/Pearson%27s_chi-squared_test)
- [Visualization of a confidence interval generated by R code](https://commons.wikimedia.org/wiki/File:Confidence-interval.svg)
- [Expected value of a squared standard normal](https://math.stackexchange.com/questions/264061/expected-value-calculation-for-squared-normal-distribution) (it's 1 - which is why the expected value of a Chi-Squared with $n$ degrees of freedom is $n$, as it's the sum of $n$ squared standard normals)