<a href="https://colab.research.google.com/github/yestrella14/DS-Unit-1-Sprint-2-Statistics/blob/master/LS_DS_122_Chi2_Tests_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment - Practice Chi^2 Tests

Use the following dataset relating to math scores of students in two different Portugese schools:

<https://archive.ics.uci.edu/ml/datasets/Student+Performance>

### 1) Load the dataset specifically relating to math scores as a new dataframe.

There are two datasets in the `student.zip` file, make sure you use `student-mat.csv`.


In [1]:
# YOUR WORK HERE
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip

--2020-07-31 00:08:38--  https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20478 (20K) [application/x-httpd-php]
Saving to: ‘student.zip.1’

student.zip.1       100%[===================>]  20.00K  --.-KB/s    in 0.1s    

2020-07-31 00:08:38 (146 KB/s) - ‘student.zip.1’ saved [20478/20478]



In [2]:
!unzip student.zip

Archive:  student.zip
replace student-mat.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace student-por.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace student-merge.R? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace student.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename: n


In [5]:
#Import the libraries
import numpy as np
import pandas as pd
from scipy.stats import chisquare #one way chi squared test


In [7]:
#Read the dataset

students1 = pd.read_csv('student-mat.csv', sep=';')
print(students1.shape)
students1.tail(3)

(395, 33)


school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
392     MS   M   21       R     GT3       T  ...     3       3        3  10   8   7
393     MS   M   18       R     LE3       T  ...     4       5        0  11  12  10
394     MS   M   19       U     LE3       T  ...     3       5        5   8   9   9

[3 rows x 33 columns]

In [8]:
students1['age'].value_counts()

16    104
17     98
18     82
15     82
19     24
20      3
22      1
21      1
Name: age, dtype: int64

In [9]:
students1.describe()

age        Medu        Fedu  ...          G1          G2          G3
count  395.000000  395.000000  395.000000  ...  395.000000  395.000000  395.000000
mean    16.696203    2.749367    2.521519  ...   10.908861   10.713924   10.415190
std      1.276043    1.094735    1.088201  ...    3.319195    3.761505    4.581443
min     15.000000    0.000000    0.000000  ...    3.000000    0.000000    0.000000
25%     16.000000    2.000000    2.000000  ...    8.000000    9.000000    8.000000
50%     17.000000    3.000000    2.000000  ...   11.000000   11.000000   11.000000
75%     18.000000    4.000000    3.000000  ...   13.000000   13.000000   14.000000
max     22.000000    4.000000    4.000000  ...   19.000000   19.000000   20.000000

[8 rows x 16 columns]

In [10]:
students1.describe(exclude='number')

school  sex address famsize  ... nursery higher internet romantic
count     395  395     395     395  ...     395    395      395      395
unique      2    2       2       2  ...       2      2        2        2
top        GP    F       U     GT3  ...     yes    yes      yes       no
freq      349  208     307     281  ...     314    375      329      263

[4 rows x 17 columns]

### 2) Use Chi^2 tests and `stats.chi2_contingency()` to identify:
 - Two pairs of variables that are dependent (are associated with one another).
 - Two pairs of variables that are independent (have no significant relationship).

Does it make intuitive sense why the variables in these pairs might or might not show a relationship to one another? 


In [12]:
# YOUR WORK HERE
from scipy import stats


Two pairs of variables that are dependent (are associated with one another)

In [13]:
#lets take a look at absence and travel-time. Asumming that there is a relationship between number of absence and travel time

In [14]:
#home to school travel time (numeric: 1 - <15 min., 2 - 15 to 30 min., 3 - 30 min. to 1 hour, or 4 - >1 hour)
students1['traveltime'].value_counts()

1    257
2    107
3     23
4      8
Name: traveltime, dtype: int64

In [15]:
students1['absences'].value_counts()

0     115
2      65
4      53
6      31
8      22
10     17
14     12
12     12
3       8
7       7
16      7
18      5
5       5
20      4
22      3
13      3
1       3
9       3
11      3
15      3
23      1
24      1
21      1
25      1
56      1
26      1
28      1
30      1
17      1
38      1
40      1
54      1
19      1
75      1
Name: absences, dtype: int64

In [16]:
absences_labels= ['0-9', '10-19', '20-29', '30-39', '40-49', '50-59', '60-69', '70-79']
absences_cutpoints = [0, 9, 19, 29, 39, 49, 59, 69, 100]

students1['absences_categories'] = pd.cut(students1['absences'], absences_cutpoints, labels=absences_labels)
students1['absences_categories'].value_counts()

0-9      197
10-19     64
20-29     13
50-59      2
30-39      2
70-79      1
40-49      1
60-69      0
Name: absences_categories, dtype: int64

In [17]:
contingency_table_Travel_Absences = pd.crosstab(students1['traveltime'], students1['absences_categories'], margins=True)

contingency_table_Travel_Absences

absences_categories  0-9  10-19  20-29  30-39  40-49  50-59  70-79  All
traveltime                                                             
1                    125     49      6      0      1      2      0  183
2                     54     13      5      2      0      0      1   75
3                     14      1      2      0      0      0      0   17
4                      4      1      0      0      0      0      0    5
All                  197     64     13      2      1      2      1  280

In [18]:
observed = pd.crosstab(students1['traveltime'], students1['absences_categories']).values
print(observed.shape)
observed

(4, 7)


array([[125,  49,   6,   0,   1,   2,   0],
       [ 54,  13,   5,   2,   0,   0,   1],
       [ 14,   1,   2,   0,   0,   0,   0],
       [  4,   1,   0,   0,   0,   0,   0]])

In [21]:
chi_squared, p_value, dof, expected1 =stats.chi2_contingency(observed)
print(f"Chi-Squared: {chi_squared}")
print(f"P-Value: {p_value}")
print(f"Degree of Freedom: {dof}")
print(f"Expected: {expected1}")

Chi-Squared: 18.218216601393372
P-Value: 0.4413665325071191
Degree of Freedom: 18
Expected: [[1.28753571e+02 4.18285714e+01 8.49642857e+00 1.30714286e+00
  6.53571429e-01 1.30714286e+00 6.53571429e-01]
 [5.27678571e+01 1.71428571e+01 3.48214286e+00 5.35714286e-01
  2.67857143e-01 5.35714286e-01 2.67857143e-01]
 [1.19607143e+01 3.88571429e+00 7.89285714e-01 1.21428571e-01
  6.07142857e-02 1.21428571e-01 6.07142857e-02]
 [3.51785714e+00 1.14285714e+00 2.32142857e-01 3.57142857e-02
  1.78571429e-02 3.57142857e-02 1.78571429e-02]]


Two pairs of variables that are independent (have no significant relationship)


In [22]:
students1['internet']

0       no
1      yes
2      yes
3      yes
4       no
      ... 
390     no
391    yes
392     no
393    yes
394    yes
Name: internet, Length: 395, dtype: object

In [28]:
students1['age'].value_counts()

16    104
17     98
18     82
15     82
19     24
20      3
22      1
21      1
Name: age, dtype: int64

In [30]:
students1['internet1'] = students1['internet'].map({'yes': 1, 'no': 0})


age_labels= ['14-15', '16-17', '18-19', '20-21']
age_cutpoints = [0, 15, 17, 19, 30]

students1['age_categories'] = pd.cut(students1['age'], age_cutpoints, labels=age_labels)
students1['age_categories'].value_counts()

16-17    202
18-19    106
14-15     82
20-21      5
Name: age_categories, dtype: int64

In [32]:
observed2 = pd.crosstab(students1['internet1'], students1['age_categories']).values
print(observed.shape)
observed

(2, 4)


array([[  9,  35,  19,   3],
       [ 73, 167,  87,   2]])

In [33]:
chi_squared, p_value, dof, expected1 =stats.chi2_contingency(observed2)
print(f"Chi-Squared: {chi_squared}")
print(f"P-Value: {p_value}")
print(f"Degree of Freedom: {dof}")
print(f"Expected: {expected1}")

Chi-Squared: 8.8379215872804
P-Value: 0.03152525777140584
Degree of Freedom: 3
Expected: [[ 13.70126582  33.75189873  17.71139241   0.83544304]
 [ 68.29873418 168.24810127  88.28860759   4.16455696]]


### 3) Use NumPy to perform your own chi^2 test "from scratch" 

Pick any of the chi^2 tests that you ran in part 2 and try them on your own. You should get the same results that Scipy got for all four values returned from `chi2_contingency()`

In [47]:
# YOUR WORK HERE
contingency_table_Travel_Absences = pd.crosstab(students1['traveltime'], students1['absences_categories'], margins=True)

contingency_table_Travel_Absences

absences_categories  0-9  10-19  20-29  30-39  40-49  50-59  70-79  All
traveltime                                                             
1                    125     49      6      0      1      2      0  183
2                     54     13      5      2      0      0      1   75
3                     14      1      2      0      0      0      0   17
4                      4      1      0      0      0      0      0    5
All                  197     64     13      2      1      2      1  280

In [48]:
travel_row_sums = contingency_table.iloc[0:4, 7].values
absences_col_sums = contingency_table.iloc[4, 0:7].values

print(travel_row_sums)
print(absences_col_sums)

[183  75  17   5]
[197  64  13   2   1   2   1]


In [49]:
total = contingency_table.loc['All','All']
total

280

In [51]:
expected = []
for i in range(len(travel_row_sums)):
    expected_row = []
    for column in absences_col_sums:
        expected_val = column*travel_row_sums[i]/total
        expected_row.append(expected_val)
    expected.append(expected_row)
    
expected = np.array(expected)
print(expected.shape)  
print(expected)

(4, 7)
[[1.28753571e+02 4.18285714e+01 8.49642857e+00 1.30714286e+00
  6.53571429e-01 1.30714286e+00 6.53571429e-01]
 [5.27678571e+01 1.71428571e+01 3.48214286e+00 5.35714286e-01
  2.67857143e-01 5.35714286e-01 2.67857143e-01]
 [1.19607143e+01 3.88571429e+00 7.89285714e-01 1.21428571e-01
  6.07142857e-02 1.21428571e-01 6.07142857e-02]
 [3.51785714e+00 1.14285714e+00 2.32142857e-01 3.57142857e-02
  1.78571429e-02 3.57142857e-02 1.78571429e-02]]


In [52]:
observed = pd.crosstab(students1['traveltime'], students1['absences_categories']).values
print(observed.shape)
observed

(4, 7)


array([[125,  49,   6,   0,   1,   2,   0],
       [ 54,  13,   5,   2,   0,   0,   1],
       [ 14,   1,   2,   0,   0,   0,   0],
       [  4,   1,   0,   0,   0,   0,   0]])

In [53]:
chi_squared = ((observed - expected)**2/(expected)).sum() 
print(f"Chi-Squared: {chi_squared}")

Chi-Squared: 18.218216601393372


In [55]:
chi_squared, p_value, dof, expected = stats.chi2_contingency(observed)

print(f"Chi-Squared: {chi_squared}")
print(f"P-value: {p_value}")
#print(f"Degrees of Freedom: {dof}") 
#print("Expected: \n", np.array(expected))

Chi-Squared: 18.218216601393372
P-value: 0.4413665325071191


## Stretch goals:

### 1. Refactor your code so it is elegant, readable, and holds reusable code in functions.

In [ ]:
# YOUR WORK HERE



### 2. Check For Understanding - Study and write your own explanations/definitions for these topics:

- What is a sample "estimate" in statistics?

- What are hypothesis test? How are they useful?

- What is a "null hypothesis?"

- What is a p-value and what does it represent?

- What does it mean for something to be "statistically significant?"

- What is a test statistic and how does it relate to a p-value?

- What are "degrees of freedom" and how are they calculated in a 1-sample, 2-sample, and chi^2 test for independence?

## Resources

- [Interactive visualize the Chi-Squared test](https://homepage.divms.uiowa.edu/~mbognar/applets/chisq.html)
- [Calculation of Chi-Squared test statistic](https://en.wikipedia.org/wiki/Pearson%27s_chi-squared_test)
- [Visualization of a confidence interval generated by R code](https://commons.wikimedia.org/wiki/File:Confidence-interval.svg)
- [Expected value of a squared standard normal](https://math.stackexchange.com/questions/264061/expected-value-calculation-for-squared-normal-distribution) (it's 1 - which is why the expected value of a Chi-Squared with $n$ degrees of freedom is $n$, as it's the sum of $n$ squared standard normals)